### ISSUE TITLE
Disable MX check

### ISSUE THREAD

**Issue by zertex** [jesselpalmer/node-email-verifier#5]
Can you add disable MX check param for emailValidator function?

**Comment by jesselpalmer** [comment]
Gotcha! What would you think about adding a flag as a parameter or a new method that doesn't check MX records? My main concern was the point of the library was to make sure that people were using real email addresses and not entering fake email addresses. I could see where that would be problematic in testing. I usually just use `@example.com` for testing email addresses.

**Comment by jesselpalmer** [comment]
@zertex Gotcha! I opened up a PR, #6, to add the parameter! Feel free to let me know what you think. If you are good with the change, I'll get a new release out. Thank you!

**Comment by jesselpalmer** [comment]
@zertex The update version has been released (1.1.0) and is available on npm! Thank you so much for the suggestion, and feel free to ping me if you need anything else!
